### ISSUE TITLE
Dependencies and folders

### ISSUE THREAD

**Issue by borgr** [roeeaharoni/sprp-acl2018#1]
Hi,
I am trying to reproduce one of the experiments experiments as is.
Right at the start running sprp_onmt_copy_128_relations_split/preproc.sh I find that I lack some file (base_folder//git/Split-and-Rephrase/baseline-seq2seq-RDFs-relations/train.complex'), I guess it needs some output of create_new_split but I can't run it:

1. I think it would be convenient for future users if you note in the README you expect mosesdecoder, openNMT-py, Split-and-Rephrase (maybe other dependencies I did not meet until now?)  to be cloned to the folder base_path + /git
2. what is `import src` trying to import in create_new_split?
3. a list of scripts to run one after the other might be also helpful (train and evaluation is perhaps trivial, but there are many kinds of data and the data itself should be constructed, which make it harder to follow)
4. I am not sure I understand how to acquire all the folders that create_new_split calls to, e.g. should lines 22-24 in create_new_split point to the place they do, and not to something like 

```  os.system('python {}/sprp-acl2018/src/data/prepare-baseline-data-RDFs-relations.py'.format(base_path))

    os.system('python {}/sprp-acl2018/src/data/prepare-evaluation-directories-RDFs-relations.py'.format(
        base_path))```

**Comment by roeeaharoni** [comment]
Hi, sorry for the inconvenience!

The (compressed) data is available in the /data directory so you don’t need
to run create_new_split, just extract the files and change the paths
accordingly in the model scripts. I will improve the README as you
suggested.

Let me know if you have any other questions!

**Comment by borgr** [comment]
Thanks, 
In this case note that open-NMT requires torchtext 0.3 (as the official release is 0.2.3) 
installed currently by
`pip install https://github.com/pytorch/text/archive/master.zip`

and that if I understand correctly the zip data file has the word split which should be deleted upon extraction (as the preprocessing expects a similar dir without the word split)

**Comment by borgr** [comment]
Apart from various changes in directories, you may also add spacy to the dependencies.
More importantly, note that the training steps parameter in train.sh should be changed from 20 to something more reasonable (how did you apply early stopping? shouldn't it replace the number of steps parameter somehow?)

**Comment by borgr** [comment]
Also validation fails for me (with some cuda errors but also) with 
IOError: [Errno 2] No such file or directory: '/cs/snapless/oabend/borgr/max//git/Split-and-Rephrase/benchmark/complex-sents/validation-rdfs-relations.id'

what should have created this file?

**Comment by conorg000** [comment]
Hi @borgr I'm stuck at the same spot - did you ever happen to come across a solution? I'm wondering if it's a file from Narayan et al.'s repo?

**Comment by conorg000** [comment]
Looks like it comes from a directory in Narayan et al.'s WebSplit v 0.1 (since removed)
" "complex-sents" directory: Train, Development and Test complex sentences used as input during testing. (Removed) " [https://github.com/shashiongithub/Split-and-Rephrase]
Do you have a recommended way to go about validation @roeeaharoni ? Thanks for your time.

**Comment by roeeaharoni** [comment]
Added the missing "complex_sents" directory as a zip file under the /data directory.

**Comment by roeeaharoni** [comment]
> Apart from various changes in directories, you may also add spacy to the dependencies.
> More importantly, note that the training steps parameter in train.sh should be changed from 20 to something more reasonable (how did you apply early stopping? shouldn't it replace the number of steps parameter somehow?)

Regarding the fixed number of steps, I chose the best model on the dev set out of the 20 epochs. This could be tuned further.
