### ISSUE TITLE
Specify the version of OpenNMT used

### ISSUE THREAD

**Issue by masashi-y** [roeeaharoni/sprp-acl2018#2]
I cannot run the experiments in src/training_scripts because there are command line options used in running train.py of OpenNMT but which seem out-dated, -start_checkpoint_at for example.
Which version of OpenNMT did you use?

**Comment by roeeaharoni** [comment]
Hi Masashi,

As mentioned in the paper, we used commit d4ab35a of the opennmt repo.

Let me know if you have any further questions,
Roee

**Comment by masashi-y** [comment]
Hi, Sorry that I did not notice that! I have trained successfully one of your models. Thanks!
