### ISSUE TITLE
OpenNMT translate.py gives empty result

### ISSUE THREAD

**Issue by zharenkov** [roeeaharoni/sprp-acl2018#3]
Hi,
I'm trying to use this project to simplify my input.
What I'm doing is:
Unpack zips from data folder. Take the model baseline_512_relations_split from trainging_scripts, change preprocess.py and train.py like this
```
base_path=/home/opc/sprp-acl2018/data
python /home/opc/OpenNMT-py/preprocess.py \
-train_src $base_path/baseline-seq2seq-split-RDFs-relations/train.complex \
-train_tgt $base_path/baseline-seq2seq-split-RDFs-relations/train.simple \
-valid_src $base_path/baseline-seq2seq-split-RDFs-relations/validation.complex \
-valid_tgt $base_path/baseline-seq2seq-split-RDFs-relations/validation.simple \
-save_data $base_path/baseline-seq2seq-split-RDFs-relations/baseline \
-src_seq_length 10000 \
-tgt_seq_length 10000 \
-src_seq_length_trunc 999 \
-tgt_seq_length_trunc 999 \
-dynamic_dict \
-share_vocab
```

```
base_path=/home/opc/sprp-acl2018/data/
model_name=sprp_onmt_baseline_512_relations_split
python /home/opc/OpenNMT-py/train.py \
-save_model $base_path/phrasing/models/${model_name}/${model_name} \
-data $base_path/baseline-seq2seq-split-RDFs-relations/baseline \
-global_attention mlp \
-word_vec_size 512 \
-rnn_size 512 \
-layers 1 \
-encoder_type brnn \
#-epochs 20 \
-train_steps 20 \
-seed 777 \
-batch_size 64 \
-max_grad_norm 2 \
-share_embeddings \
-gpuid 0 \
#-start_checkpoint_at 1 \
#-start_epoch 1 \
```

get latest checkpoint after training and try to call openNMT's translate.py
`python translate.py --model=/home/opc/sprp-acl2018/data//phrasing/models/sprp_onmt_baseline_512_relations_split/sprp_onmt_baseline_512_relations_split_step_25000.pt --src=/home/opc/iphoneXwiki_new.txt`

But input is empty
```
/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py:46: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
[2019-04-02 08:30:33,973 INFO] Translating shard 0.
/home/opc/anaconda3/lib/python3.6/site-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)
PRED AVG SCORE: nan, PRED PPL: nan
```

I also noticed, that after some step perplexity became very huge, and then NaN

```
[2019-04-01 20:37:33,216 INFO] Step 9550/100000; acc:  69.38; ppl: 22.56; xent: 3.12; lr: 1.00000; 1170/2069 tok/s;  18306 sec
[2019-04-01 20:39:10,589 INFO] Step 9600/100000; acc:  11.45; ppl: 1573654815.57; xent: 21.18; lr: 1.00000; 1082/1957 tok/s;  18404 sec
[2019-04-01 20:41:14,334 INFO] Step 9650/100000; acc:   3.99; ppl: 29072175532478435328.00; xent: 44.82; lr: 1.00000; 902/1620 tok/s;  18528 sec

```

Also I tried to train baseline_128 model but the output of translate looks like this
```
SENT 42: ['On', 'the', 'front', 'of', 'the', 'phone,', 'a', '7-megapixel', 'TrueDepth', 'camera', 'has', 'an', 'f/2.2', 'aperture,', 'and', 'features', 'face', 'detection', 'and', 'HDR.']
PRED 42: . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
PRED SCORE: -50.4453
```

Maybe I'm doing something wrong?
I'll appreciate any advice.
Thanks!

**Comment by zharenkov** [comment]
I tried different combinations of pytorch, torchtext version.
Now I've got
pytorch == 0.4.0
torchtext ==0.2.3
OpenNMT checked out on specified in readme commit

preproc.sh works well, but when I'm running train.sh
I get this error message

```

Loading train dataset from /home/opc/sprp-acl2018/data/baseline-seq2seq-split-RDFs-relations/baseline.train.1.pt, number of examples: 1039392
 * vocabulary size. source = 2879; target = 2879
Building model...
/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py:38: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.3 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Intializing model parameters.
Traceback (most recent call last):
  File "/home/opc/OpenNMT-py/train.py", line 417, in <module>
    main()
  File "/home/opc/OpenNMT-py/train.py", line 401, in main
    model = build_model(model_opt, opt, fields, checkpoint)
  File "/home/opc/OpenNMT-py/train.py", line 343, in build_model
    use_gpu(opt), checkpoint)
  File "/home/opc/OpenNMT-py/onmt/ModelConstructor.py", line 222, in make_base_model
    model.cuda()
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 112, in _apply
    self.flatten_parameters()
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 78, in flatten_parameters
    if not any_param.is_cuda or not torch.backends.cudnn.is_acceptable(any_param):
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 92, in is_acceptable
    if _libcudnn() is None:
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 58, in _libcudnn
    'but linked against {}'.format(compile_version, __cudnn_version))
RuntimeError: cuDNN version mismatch: PyTorch was compiled against 7102 but linked against 7301
```

**Comment by roeeaharoni** [comment]
Hi,

This seems like a Pytorch issue - I would recommend asking in their forum about how to solve this version mismatch.

I would also recommend using this dataset: https://github.com/google-research-datasets/wiki-split
If you are interested in obtaining better results for sentence splitting.

Hope this helps,
Roee

**Comment by zharenkov** [comment]
Thanks, I downgrade cudnn lib, training started but then failed with error

```

Loading train dataset from /home/opc/sprp-acl2018/data/baseline-seq2seq-split-RDFs-relations/baseline.train.1.pt, number of examples: 1039392
/home/opc/OpenNMT-py/onmt/modules/GlobalAttention.py:177: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  align_vectors = self.sm(align.view(batch*targetL, sourceL))
/home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py:91: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
/home/opc/OpenNMT-py/onmt/Loss.py:145: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
  return onmt.Statistics(loss[0], non_padding.sum(), num_correct)
Traceback (most recent call last):
  File "/home/opc/OpenNMT-py/train.py", line 417, in <module>
    main()
  File "/home/opc/OpenNMT-py/train.py", line 409, in main
    train_model(model, fields, optim, data_type, model_opt)
  File "/home/opc/OpenNMT-py/train.py", line 231, in train_model
    train_stats = trainer.train(train_iter, epoch, report_func)
  File "/home/opc/OpenNMT-py/onmt/Trainer.py", line 174, in train
    report_stats, normalization)
  File "/home/opc/OpenNMT-py/onmt/Trainer.py", line 305, in _gradient_accumulation
    trunc_size, self.shard_size, normalization)
  File "/home/opc/OpenNMT-py/onmt/Loss.py", line 125, in sharded_compute_loss
    loss.div(normalization).backward()
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```

**Comment by kaustumbh7** [comment]
> Thanks, I downgrade cudnn lib, training started but then failed with error
> 
> ```
> 
> Loading train dataset from /home/opc/sprp-acl2018/data/baseline-seq2seq-split-RDFs-relations/baseline.train.1.pt, number of examples: 1039392
> /home/opc/OpenNMT-py/onmt/modules/GlobalAttention.py:177: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
>   align_vectors = self.sm(align.view(batch*targetL, sourceL))
> /home/opc/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py:91: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
>   input = module(input)
> /home/opc/OpenNMT-py/onmt/Loss.py:145: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number
>   return onmt.Statistics(loss[0], non_padding.sum(), num_correct)
> Traceback (most recent call last):
>   File "/home/opc/OpenNMT-py/train.py", line 417, in <module>
>     main()
>   File "/home/opc/OpenNMT-py/train.py", line 409, in main
>     train_model(model, fields, optim, data_type, model_opt)
>   File "/home/opc/OpenNMT-py/train.py", line 231, in train_model
>     train_stats = trainer.train(train_iter, epoch, report_func)
>   File "/home/opc/OpenNMT-py/onmt/Trainer.py", line 174, in train
>     report_stats, normalization)
>   File "/home/opc/OpenNMT-py/onmt/Trainer.py", line 305, in _gradient_accumulation
>     trunc_size, self.shard_size, normalization)
>   File "/home/opc/OpenNMT-py/onmt/Loss.py", line 125, in sharded_compute_loss
>     loss.div(normalization).backward()
>   File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
>   File "/home/opc/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
> ```

This error can be resolved by specifying an argument in - 
`loss.div(normalization).backward(retain_graph=True)` in   `File "/home/opc/OpenNMT-py/onmt/Loss.py", line 125, in sharded_compute_loss`

**Comment by bhavikapanara** [comment]
@roeeaharoni  Can you please share the trained models so that I don't need to train it.

Thanks,
Bhavika
