### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by kaustumbh7** [roeeaharoni/sprp-acl2018#4]
I am trying to run the following script, 
`sprp-acl2018/src/training_scripts/sprp_onmt_baseline_128/train.sh` but facing some errors. What versions of Pytorch and Torchtext are required to run the script correctly ?

**Comment by roeeaharoni** [comment]
As mentioned, this uses openNMT-py commit d4ab35a. This is from February 2018, so I'd look at the stable versions from then.
